service: sqs
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  iam:
    role:
      statements:
        - Effect: Allow
          Principal:
            Service: "sns.amazonaws.com"
          Action:
            - sqs:SendMessage
          Resource:
            - Fn::GetAtt: [receiverQueue, Arn]
          Condition:
            ArnEquals:
              aws:SourceArn: "arn:aws:sns:us-east-1:706512677771:Topic-response"

functions:
  producer:
    handler: handler.producer
    events:
      - http:
          method: post
          path: producer

  consumer:
    handler: handler.consumer
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - receiverQueue
              - Arn
  # receiverError:
  #   handler: handler.DLQ
  #   events:
  #     - sqs:
  #         arn:
  #           Fn::GetAtt:
  #             - MyQueue
  #             - Arn
  #     - batchSize: 1 # defaul
resources:
  Resources:
    receiverQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: receiverQueue
